// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIutdRrzH3L7FOse0xv4TgE70ZgIr3cJs',
    appId: '1:356157128310:web:477385c1152fa247c1a957',
    messagingSenderId: '356157128310',
    projectId: 'sem3-minor',
    authDomain: 'sem3-minor.firebaseapp.com',
    storageBucket: 'sem3-minor.firebasestorage.app',
    measurementId: 'G-13EDVRWG8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0xGlkP-SQhllZL3HeepdWoaJEyD38Kvg',
    appId: '1:356157128310:android:a0beba04d3f31488c1a957',
    messagingSenderId: '356157128310',
    projectId: 'sem3-minor',
    storageBucket: 'sem3-minor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATTOEH0l9znyDAhR_zXhnoSWr-heJeG9I',
    appId: '1:356157128310:ios:109480c0de6ac43cc1a957',
    messagingSenderId: '356157128310',
    projectId: 'sem3-minor',
    storageBucket: 'sem3-minor.firebasestorage.app',
    iosBundleId: 'com.example.drop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATTOEH0l9znyDAhR_zXhnoSWr-heJeG9I',
    appId: '1:356157128310:ios:109480c0de6ac43cc1a957',
    messagingSenderId: '356157128310',
    projectId: 'sem3-minor',
    storageBucket: 'sem3-minor.firebasestorage.app',
    iosBundleId: 'com.example.drop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIutdRrzH3L7FOse0xv4TgE70ZgIr3cJs',
    appId: '1:356157128310:web:143f6b7d61875753c1a957',
    messagingSenderId: '356157128310',
    projectId: 'sem3-minor',
    authDomain: 'sem3-minor.firebaseapp.com',
    storageBucket: 'sem3-minor.firebasestorage.app',
    measurementId: 'G-483ZLBHYDQ',
  );

}